### ISSUE TITLE
Change Medicago truncatula chromosome names in GWAS files on DSCensor

### ISSUE THREAD

**Issue by svengato** [legumeinfo/ZBrowse#2]
Was 1-8, should be chr1-chr8

**Comment by adf-ncgr** [comment]
it must have been a silent chr.

**Comment by svengato** [comment]
I changed them in the organism file and my remaining local GWAS files. This eliminates species-dependent hard-coding when parsing chromosome names in build.annotations().

**Comment by adf-ncgr** [comment]
OK great. I think my task here properly ought to be getting the medicago GWAS into the datastore using the new file formats, so that's what I'll do (eventually)

**Comment by svengato** [comment]
My mistake - the Medicago truncatula chromosome names are already in the expected format. I have corrected this in commit 38896d5...
