### ISSUE TITLE
datastore refactor causing user angst?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/ZBrowse#32]
![image](https://user-images.githubusercontent.com/2009605/118276932-76b2a000-b485-11eb-9d21-451dd0c9f220.png)

(things seem to be otherwise functional)

**Comment by svengato** [comment]
This affects creation of new GWAS (and in theory, QTL) datasets from the files in the data store. It is on my list of things to refactor when the data store settles down.

**Comment by svengato** [comment]
What this does is test whether a certain file exists in the LIS data store, and the one we used originally no longer exists. I (locally and on dev-legfedorg, but not in production) changed it to another file in mid-April, but have not yet checked it in.

**Comment by svengato** [comment]
Part of commit 46bcb44, though it would be nice to use more generic/permanent URLs.
