### ISSUE TITLE
publication info in Manage tab?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/ZBrowse#33]
not sure this is worth a ton of effort, but I noticed that the set of columns displayed in the Manage tab is slightly inconsistent with what's shown in the Data Table tab, notably with respect to the source of the displayed rows ("publication"). If it's easy to make them consistent, it's probably worth doing at some point.

**Comment by svengato** [comment]
I think the table in the Manage tab was supposed to be a reduced summary (at least in original ZBrowse), but this should be easy to change.

**Comment by adf-ncgr** [comment]
Having a reduced summary makes sense, although I think I would handle it differently. Let's maybe discuss further before you do anything on it.

**Comment by svengato** [comment]
This overlaps with issue #39.
