### ISSUE TITLE
Provision for Single Dataset View

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/ZBrowse#38]
Sometimes it is desirable to look at a single dataset without having to compare to another dataset. 
If possible and makes sense, making provisions for hiding/showing a panel, so that only needded panels are displayed.

**Comment by svengato** [comment]
I added a "Two Species" switch at the top left of the Manage tab. This toggles species 2, Swap Datasets, genomic linkage, and macrosynteny.

Known issues:
- For now, it only toggles the display, it does not clear any existing two-species data like genomic linkage.
- I need to investigate what happens during tour steps related to the disabled views.

**Comment by svengato** [comment]
It should also update to/from the URL (to do: add a twoSpecies=[y|n] field).

**Comment by svengato** [comment]
It now updates to and from the URL, for example you can input something like

http://dev.lis.ncgr.org:50071/ZZBrowse/?tab=Manage&species=1&datasets=Peanut%20GWAS&chr=Arahy.01&selected=100000&window=250000

The species (= 1 or 2) tag is optional, if missing it implies that ZZBrowse should display both species. Let me know if this does not work as expected.

**Comment by sdash-github** [comment]
I just tested and it behaves as you described.
An observation:
I revised to species=2 from species=1 and it did displayed both species 
panels and in the URL the parameter '&species=' disappeared. It doesn't 
affect what I want to see in these panels but just wanted to alert you 
that this is happening as intended. I am not worried about it at all now.

Thanks for getting it done in time.

Sudhansu

**Comment by svengato** [comment]
> An observation:
> I revised to species=2 from species=1 and it did displayed both species 
> panels and in the URL the parameter '&species=' disappeared. It doesn't 
> affect what I want to see in these panels but just wanted to alert you 
> that this is happening as intended. I am not worried about it at all now.

Great - let me know if you prefer to always see the "species=" tag, it is easy enough to change that.

Also, would "twoSpecies=y/n" be less confusing than "species=1/2"? Someone might try "species=peanut", for example.

**Comment by sdash-github** [comment]
I like "twoSpecies=y/n".
But like said this is not urgent at all-- do it if you want to. The 
primary need has already been achieved y you, one or two species panels.

Sudhansu

**Comment by svengato** [comment]
> I like "twoSpecies=y/n".
> But like said this is not urgent at all-- do it if you want to. The 
> primary need has already been achieved y you, one or two species panels.

Done. Try

http://dev.lis.ncgr.org:50071/ZZBrowse/?tab=Manage&twoSpecies=n&datasets=Peanut%20GWAS&chr=Vr01&selected=100000&window=250000

or toggling the Two Species checkbox by hand.

**Comment by svengato** [comment]
Known issue: when Two Species is turned off, the Genomic Linkage button still appears in the linkouts dialog, which is not aware of the checkbox state - could be tricky to fix.

**Comment by svengato** [comment]
Added in commit 61abf99.

**Comment by svengato** [comment]
> Known issue: when Two Species is turned off, the Genomic Linkage button still appears in the linkouts dialog, which is not aware of the checkbox state - could be tricky to fix.

Fixed in commit d6be90e.
