### ISSUE TITLE
A title of the dataset would be helpful

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/ZBrowse#39]
The left side panel dropdown currently shows the species of the dataset and the 'About' info comes from going to the 'Data Table' (not so intuitive to guess where to go) tab and looking at the author-year info and going to the title of the pub.  And if the publication is missing like in case of pigeonpea-- only currently though-- it is difficult to guess unless one studies the traits info to make a guess about the dataset.

It will be nice to have a short title for the dataset during our curation and data loading  and will save trouble of visiting other places to get this info. This will be particularly helpful in the long run when we have multiple datasets per species.

**Comment by svengato** [comment]
For example, add a summary of each publication, as a tooltip that displays when you mouseover the publication in the Data Table view.

**Comment by svengato** [comment]
These GWAS datasets (in the data store) are not included in the ZZBrowse soybean GWAS dataset. Is this intentional?
Hu, Zhang, et al. 2014
Li, Zhao, et al. 2018

(noticed while inserting the synopsis in the GWAS datasets)

**Comment by svengato** [comment]
I made a first cut at this, pictures are below. (I cannot copy the revised GWAS and QTL data files to dev-zzbrowse yet - reminder to Andrew to give me access.) Let me know if this is on the right track.

Manage tab - the list of sources appears under the summary table. This may be quite long (as for soybean).

![manage](https://user-images.githubusercontent.com/8918336/141711610-8c403677-ed8b-4bc1-978f-46152905f6eb.png)

Data table tab - mouseover the Publication column to display the synopsis.

![data-table](https://user-images.githubusercontent.com/8918336/141711713-744b6ecb-22d2-48ea-be40-9d237845f68b.png)

**Comment by adf-ncgr** [comment]
not intentional as far as I'm aware. It is probably the fact that the PlatformName that is given to them doesn't match a marker dataset that is causing them to stick in your craw. I suspect that mixed.gwas.Li_Zhao_2018 is supposed to be paired with Wm82.gnm2.mrk.Li_Zhao_2019 but it seems a bit odd that the years given don't match. It looks like mixed.gwas.Hu_Zhang_2014 may just be an oddball, probably safe to just let it be.

**Comment by adf-ncgr** [comment]
you should already have access to dev-zzbrowse. I just made you a home dir in case that was the sticking point.

**Comment by svengato** [comment]
I will get back to it when I redo the data processing. I noticed other flaws as well, like a cowpea QTL study with no authors - should be able to track them down from the title though.

**Comment by svengato** [comment]
That worked - I guess dev-zzbrowse is not a good place to be homeless.

**Comment by svengato** [comment]
You can now view the synopsis information on dev-zzbrowse.

**Comment by adf-ncgr** [comment]
mouseovers on the data table are nice. the listing of all GWAS for a species gets a bit long in the case of soybean, maybe that could be tucked into an expandable div (e.g. https://getbootstrap.com/docs/5.0/components/accordion/)?

**Comment by svengato** [comment]
Added in commit 445e007 (synopsis data added by hand, for now).
