### ISSUE TITLE
data tables broken?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/ZBrowse#46]
https://zzbrowse.legumeinfo.org/?tab=Table&twoSpecies=y&datasets=Common%20Bean%20GWAS&chr=Chr01&selected=100000&window=250000&datasets2=Arabidopsis%20thaliana%20GWAS&chr2=1&selected2=100000&window2=250000&traitsFromOntology=y&traitsFromOntology2=y&macroMatched=20&macroIntermediate=10&macroMask=10&macroDistance=levenshtein
<img width="432" alt="image" src="https://github.com/legumeinfo/ZZBrowse/assets/2009605/7c183f65-6616-4e51-9908-8737ab02dfd8">

**Comment by svengato** [comment]
POST requests involving those data tables return 500 (Internal Error).

ZZBrowse log file says
```
Warning in file(open = "w+b", encoding = "UTF-8") :
  cannot open file '/tmp/RtmpKUwFIb/Rf5fe5badf217': No such file or directory
Error in file(open = "w+b", encoding = "UTF-8") :
  cannot open the connection
```

Created `/tmp/RtmpKUwFIb` directory by hand, and `chown`ed it to `shiny:shiny`. Now the POSTs return 200 (OK) and the data appear in the table, as expected.

Removed that directory, the problem returned.
Recreated it, the problem went away.

Consider this a temporary fix?

**Comment by svengato** [comment]
The problem has reappeared, I will look at `shiny`'s permissions.

**Comment by svengato** [comment]
Solution: Create a temporary directory just for the `shiny` user.
```
sudo mkdir /tmp/shiny-server
sudo chown shiny:shiny /tmp/shiny-server
sudo chmod 700 /tmp/shiny-server
```

Specify this temporary directory in its `.Renviron` file (create one if it does not yet exist).
```
sudo vi /home/shiny/.Renviron
  # add this line:
  TMPDIR=/tmp/shiny-server
sudo chown shiny:shiny /home/shiny/.Renviron
```

Then restart shiny-server,
```
sudo systemctl restart shiny-server
```
