### ISSUE TITLE
Remove scaffold matches when constructing related regions

### ISSUE THREAD

**Issue by svengato** [legumeinfo/ZBrowse#9]
Since we only display the chromosomes, these are not valid matches. They can also cause errors due to the apparent chromosome number exceeding the real number of chromosomes.

Example: the current pigeonpea annotations have "chromosomes" like cajca.ICPL87119.gnm1.Scaffold000011 which falsely implies a match on chromosome 11, and cajca.ICPL87119.gnm1.Scaffold117496 when there is no chromosome 117496.

**Comment by adf-ncgr** [comment]
Doesn't the enumeration of chromosomes with their lengths in the organisms file (IIRC) effectively take care of this?
I should note that we also have a sort of plan to produce files for the datastore that will clearly differentiate chromosomes from non-chromosomes, though we're being slow to move forward with it.

**Comment by svengato** [comment]
If I understand it correctly, the genomic linkage results may have different chromosome names than those in ZBrowse, so we match them by extracting the chromosome number and converting that to the chromosome name. Hence the above errors can happen.

I can fix this by removing candidate results whose chromosome name contains "scaf", but will look for a better solution before checking it in.

**Comment by adf-ncgr** [comment]
well, I really want to move to not having different chromosome names in genomic linkage and ZBrowse. Or at least, if there are differences, they should be ultra-methodical across species and not ad hoc per species.

**Comment by adf-ncgr** [comment]
So for pigeonpea, if changing the organisms file to have names like CcLG02 would solve it, that's my preferred solution.

**Comment by svengato** [comment]
Okay, I looked more closely at the details. Even if we take the last part of the full chromosome name, there are still a few discrepancies.
(Z) ZBrowse format (from organism and annotations files)
(L) Genomic linkage results
(G) input to Genome Context Viewer

Soybean
(Z) Gm01
(L) glyma.Chr01
(G) glyma.Chr01

Common bean
(Z) Chr01
(L) phavu.Chr01
(G) phavu.Chr01

Pigeonpea
(Z) 1
(L) cajca.CcLG01
(G) cajca.CcLG01
Note that we get the pigeonpea annotations from a csv file, which also has a "full chromosome" column from which we could extract the CcLGnn format.

Medicago truncatula
(Z) chr2
(L) medtr.chr2
(G) medtr.chr2

Cowpea
(Z) Vu05
(L) vigun.Vu05
(G) vigun.Chr05

**Comment by adf-ncgr** [comment]
thanks. Common bean and Medicago truncatula look like what I'm aiming for, at least for now (the gensp. prefixing could eventually get some additional yuck-age for versioning, but we'd try to do it consistently across all genomes if we go there).
Pigeonpea we should make Z conform by doing whatever is needed so that 1 -> CcLG01; I would opt for getting the annotations from the datastore too, like the other species.
Cowpea I am a little confused- how can L and G be asymmetric since L = outputs from GCV and G = inputs to GCV? I think G really ought to be vigun.Vu05 but let me know if you think that breaks something.

For soybean there has indeed been a great battle for the hearts and minds of the soybean community over Gm01 vs Chr01. I'll have to investigate this one further, but we'll get it to conform one way or another....

**Comment by svengato** [comment]
I checked again on the development site. Cowpea from the GCV does have the form
(G) vigun.Vu05
which makes Soybean the only controversial one (Gm05 v. Chr05).

**Comment by svengato** [comment]
> Pigeonpea we should make Z conform by doing whatever is needed so that 1 -> CcLG01; I would opt for getting the annotations from the datastore too, like the other species.

Is there a preferred Cajca annotations file in the datastore? cajca.ICPL87119.gnm1.ann1.Y27M.gene_models_main.gff3.gz looks like the most recent.

**Comment by adf-ncgr** [comment]
Yes, *.gene_models_main.gff3.gz should always be the file to use for any given ann(otation).

**Comment by adf-ncgr** [comment]
Also, regarding soybean, it looks like the GCV instance you are talking to probably got its Chr01 before the Gm01 rebels took over legumeinfo. You can see the vestiges of imperial power here:
https://phytozome-next.jgi.doe.gov/jbrowse/index.html?data=genomes%2FGmax_Wm82_a2_v1&loc=Chr08%3A15162696..15165019&tracks=Transcripts%2CAlt_Transcripts%2CPASA_assembly%2CBlastx_protein%2CBlatx_FabidaeGrape&highlight=

sadly, I guess I'll have to update that GCV instance to comply with the commandeered datastore base- although I think I did hear a rumor that the Chr01 forces were regrouping... watch the battle forces amassing here:
https://soybase.org/gcv/gene;soybase=glyma.Wm82.gnm4.ann1.Glyma.15G255600?q=Glyma.15G255600&sources=soybase&sources=liu2020&algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=25&bmatched=20&bintermediate=10&bmask=10&linkage=average&cthreshold=20&neighbors=10&matched=4&intermediate=5&bregexp=&border=chromosome&regexp=&order=distance

give me a nudge if you are ready to make a new release and the old man still hasn't knocked out the tractor beam...

**Comment by svengato** [comment]
> Yes, *.gene_models_main.gff3.gz should always be the file to use for any given ann(otation).

The chromosome names in that file end in Cc01, not CcLG01. This may require some tweaking.

**Comment by adf-ncgr** [comment]
OK, sounds like I need to have a closer look- but we will let the tweaking be on the side of data, not the code. I now vaguely recall the rebels having something to say about this one as well...

**Comment by svengato** [comment]
> Also, regarding soybean, it looks like the GCV instance you are talking to probably got its Chr01 before the Gm01 rebels took over legumeinfo.

As the rebels say, you cannot spell "Thatchrite" without "Chr"!

**Comment by svengato** [comment]
I now see chromosomes like Gm01 and Cc01 on the production site, but Chr01 and CcLG01 on the development site. Do we have to update them separately there?

**Comment by adf-ncgr** [comment]
Hmm, I assumed it would be running off the same services, but maybe not. I'll have a look.

**Comment by adf-ncgr** [comment]
It looks like the GCV client hosted on dev-legfedorg was indeed living in a past world and talking to a set of GCV services that I thought had actually become defunct. So, if the issue you were observing had to do with what you saw via http://dev.lis.ncgr.org:50003/gcv/phytozome_10_2/ then I think it should be fixed. But, from a services perspective, I guess you should be talking to https://gcv-services.lis.ncgr.org/gcv2_phytozome_10_2_lis/services for all species (except arabidopsis), which should already have the fix. Anyway, let me know if any further action needed.

**Comment by svengato** [comment]
Where is that URL set, in the reverse proxy? It does not appear in the code.

I am seeing some strange behavior after changing species, it may require resetting the genomic linkage connection.

I may also change this issue's name, as it really has nothing to do with scaffold matches.

**Comment by svengato** [comment]
> Where is that URL set, in the reverse proxy? It does not appear in the code.

For genomic linkages, it comes from the organism file. Now I am getting sensible behavior for pigeonpea and soybean.

**Comment by svengato** [comment]
Except  
(a) It should still reset the genomic linkage results when you change the species,  
(b) It is still returning scaffold results for pigeonpea.

**Comment by adf-ncgr** [comment]
is a) something I broke? Or just something you need to look into? For b) I don't plan to stop returning scaffold results for any of the species (pigeonpea is most obvious because is has so many, but there are some in all species except arabidopsis at this point) so we'll need to make sure these don't break anything; my guess is that it would easy enough for you to ignore linkage results that don't match any of your chromosome names.

**Comment by svengato** [comment]
No, (a) is something we never noticed because when we were using chromosome numbers, switching from (say) pigeonpea to soybean kept us at chromosome N, position p which usually still made sense. Now when we change species, I make it reset to chromosome 1 with the default position and window width.

For (b), yes I plan to filter out chromosome names that do not match the expected format.

**Comment by adf-ncgr** [comment]
> Now when we change species, I make it reset to chromosome 1 
better yet, make it reset to the first chromosome  ;)

> For (b), yes I plan to filter out chromosome names that do not match the expected format.
sounds good, but note that expectations may change slightly when we enter the realm of multi-genome-versions

**Comment by svengato** [comment]
Current status: The plan is to use chromosome names instead of numbers (for all species except A. thaliana), and validate the species 2 chromosome names returned from the GCV (for all including A. thaliana). Everything seems to work, but I am still thinking about how to split up the changes to check in, as some of them were originally separate but are now intertwined.

**Comment by svengato** [comment]
Done, as part of commit 2c2b7c9...
